### PR TITLE
Fix layout

### PR DESCRIPTION
**Pull request by smeinecke**
This fixes some layout problems:

- grafik
  Fixes limited space in header for counters + print count in local format.
- grafik
Static size of badges to contains size, regardless if report is marked read or unread.
- grafik
Unform format of datetime regardless if localtime or utc is selected.

### CODE REVIEW

**Comment by liuch** [comment]
I would merge some of the commits from your PR, but not all. For example, I don't like the commit in which you set a css rule `width: 3em;`. What if I set the following rule: `text-transform: lowercase;` or even `text-transform: full-width;`? Maybe it should be `min-width`? But I still don't like this one. There is too little space in the table to increase the width of its elements.

**Comment by liuch** [comment]
Could you break the PR into separate logically separated entities? It would be easier to decide what to accept and what not.

**Comment by liuch** [comment]
Have a look at this: https://github.com/liuch/dmarc-srg/commit/3a48021ffbd15c15de357ae37619435bfed20e88. I have changed the colors (your are almost the same in the dark theme and too bright) and prevented a button based on a link from changing color.

**Comment by williamdes** [comment]
Hi @liuch 
Can we close this old one ?
Is the changes to the formatting already merged ?

**Pull request closed without merging**
