### PR TITLE
Add .gitattributes and .editorconfig

### PR DESCRIPTION
**Pull request by williamdes**

### CODE REVIEW

**Comment by liuch** [comment]
Hello @williamdes, thanks for the PR
.gitattributes is good, but .editorconfig doesn't fit my project code. Moreover, the coding style in .php and .js files are different.

**Comment by williamdes** [comment]
> Hello @williamdes, thanks for the PR .gitattributes is good, but .editorconfig doesn't fit my project code. Moreover, the coding style in .php and .js files are different.

That's okay I can adjust it, what are the settings for your project?

**Comment by liuch** [comment]
- JavaScript: indent_style = tab, insert_final_newline = true;
- PHP: indent_style = space, insert_final_newline = false;

**Comment by williamdes** [comment]
Well

> * JavaScript: indent_style = tab, insert_final_newline = true;
> * PHP: indent_style = space, insert_final_newline = false;

Okay, I made some changes to what you suggested to match the actual situation of files

I used `editorconfig-checker -disable-indent-size` from https://github.com/editorconfig-checker/editorconfig-checker#readme

to check if all files are following the config

**Comment by liuch** [comment]
Do you mind if I make fixes outside of your PR? It turns out that my editor automatically adds EOL to the end of the file, and I don't even see that.

**Comment by williamdes** [comment]
> Do you mind if I make fixes outside of your PR? It turns out that my editor automatically adds EOL to the end of the file, and I don't even see that.

For sure, you can work on it like the other one or merge it and do tweaks
That's okay for me
At least you have a config that's coherent with the files, now you can tweak it

**Comment by williamdes** [comment]
Merged as b51f32c8df3e7c493397b3fdac62e305ec96e303 and 7fb1d73053f86206f835f41bca2b76415e0fc5f3

**Pull request closed without merging**
