### PR TITLE
Ref #54 - Show quarantined and rejected numbers 

### PR DESCRIPTION
**Pull request by williamdes**
Described in #54

Already merged: 
- 8b3b3f40f0bf8ecff176cff892a28674b4a5f027

Left over:
- reports
- UI/css

### CODE REVIEW

**Comment by williamdes** [comment]
@liuch can we get this merged without the UI part ?

**Comment by liuch** [comment]
Do you mean add code to the backend first without UI and reports? I like this idea. Unfortunately I don't see a way to separate them in this PR.

**Comment by williamdes** [comment]
> Do you mean add code to the backend first without UI and reports? I like this idea. Unfortunately I don't see a way to separate them in this PR.

Do you want me to do two commits?
Or add CSS to hide the blocks?

**Comment by liuch** [comment]
I would accept the code for the backend immediately as a separate PR. But the Web UI and the summary report need to be discussed. I suggest eating the elephant piece by piece: the backend, the Web UI and the summary reports. Two or three PRs. Is it possible?

**Comment by williamdes** [comment]
> I would accept the code for the backend immediately as a separate PR. But the Web UI and the summary report need to be discussed. I suggest eating the elephant piece by piece: the backend, the Web UI and the summary reports. Two or three PRs. Is it possible?

Yeah sure

**Comment by williamdes** [comment]
@liuch I did split this into 3 commits
You can now cherry-pick them into master. If you add my remote into your repo
Is that okay for you ?

**Comment by liuch** [comment]
There is no problem for me to take only one commit from your branch. But then your PR will get conflict. Is that okay for you?

**Comment by williamdes** [comment]
> There is no problem for me to take only one commit from your branch. But then your PR will get conflict. Is that okay for you?

Yeah, nevermind I will rebase and get it right

**Comment by liuch** [comment]
Done.

**Comment by williamdes** [comment]
Hi @liuch
What can be done so I can stop keeping this PR up to date?

**Comment by liuch** [comment]
@williamdes First I want to implement that the user can choose which list columns to display and which not to display in the report list. Because two extra columns are added and the list gets cluttered. The same thing with the summary report.

**Comment by williamdes** [comment]
> @williamdes First I want to implement that the user can choose which list columns to display and which not to display in the report list. Because two extra columns are added and the list gets cluttered. The same thing with the summary report.

Okay, let me know
Thank you for your hard work!

**Comment by williamdes** [comment]
Hi @liuch 
I would like to clean this out of my PR list and my mind.
What can I do to get this done ?

**Comment by liuch** [comment]
Hi @williamdes 
Some of the functionality from your PR has already been implemented, perhaps in a slightly different way:

- Filtering the report list by disposition
- Summary report

It remains to implement the display of disposition in the UI. But for that I need to make other changes to the UI that I mentioned earlier. I plan to do this after I finish the user management code. I'm afraid this code (user management) and the code implementing the customization of the report list columns will cause more conflicts with your PR. You can close it if you want, I won't forget about it anyway.

**Comment by williamdes** [comment]
> You can close it if you want, I won't forget about it anyway.

Thank you! 

Let me know about this, I am looking forward to the next version 

This project is awesome!

**Comment by liuch** [comment]
I have just pushed [a commit](https://github.com/liuch/dmarc-srg/commit/7e8ae009c2fd8769935a69ab39056bddc144ace) in which I added some columns to the report list. Some of them are displayed and some are not. A little more detail can be found in the commit description. If you want to see what other columns look like, you can change the list of columns here: https://github.com/liuch/dmarc-srg/blob/7e8ae009c2fd8769935a69ab39056bddc144ace8/public/js/list.js#L172
I'll do the customization later.
Screenshot:

**Comment by williamdes** [comment]
Awesome, I will test this as soon as possible!

**Comment by liuch** [comment]
Fully completed with 2b10c602e61d0e25e770f6adc3fa39403ab31246

**Pull request closed without merging**
