### PR TITLE
Improvements and fixes

### PR DESCRIPTION
**Pull request by williamdes**

### CODE REVIEW

**Comment by liuch** [comment]
Thanks a lot!

**Comment by williamdes** [comment]
Are you interested by running the phpunit tests in GitHub CI ?
It's only a file in `.github`

With that I could also add phpstan support

**Comment by williamdes** [comment]
I also have a very well working Docker nginx PHP 8.1 Linux alpine version

**Comment by liuch** [comment]
I'd rather not be tied to a specific platform. Phpunit perfectly runs locally. But I definitely need to increase my test coverage.

> With that I could also add phpstan support

What do you mean by that?

> I also have a very well working Docker nginx PHP 8.1 Linux alpine version

I don't know enough about how docker works, and I try not to add things to the project that I don't understand. But a link to your Dockerfile can be placed in the README.md file if you like.

**Comment by williamdes** [comment]
I did open #76 for the phpstan subject
if it pleases you I may continue or at least push a script for you to play with it and improve the code base level by level

**Pull request merged**
